# Generated by Django 4.2 on 2024-10-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('unidadDeMedida', models.CharField(choices=[('kg', 'Kilogramos'), ('g', 'Gramos'), ('l', 'Litros'), ('ml', 'Mililitros'), ('u', 'Unidades'), ('paq', 'Paquete'), ('caja', 'Caja'), ('taza', 'Taza'), ('otro', 'Otro')], max_length=10)),
                ('cantidadDisponible', models.PositiveIntegerField()),
                ('cantidadMinRequerida', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precioDeVenta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precioDeCosto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechaDeElaboracion', models.DateField()),
                ('fechaDeVencimiento', models.DateField()),
                ('categoria', models.CharField(choices=[('panadería', 'Panadería'), ('pastelería', 'Pastelería')], max_length=15)),
                ('cantidadDisponible', models.PositiveIntegerField()),
                ('cantidadMinRequerida', models.PositiveIntegerField()),
            ],
        ),
    ]
