# Generated by Django 4.2 on 2024-10-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='unidadDeMedida',
            field=models.CharField(choices=[('kg', 'Kilogramos'), ('g', 'Gramos'), ('l', 'Litros'), ('ml', 'Mililitros'), ('u', 'Unidades'), ('paq', 'Paquete'), ('caja', 'Caja'), ('taza', 'Taza'), ('otro', 'Otro')], default='unidad', max_length=10),
        ),
    ]
