# Generated by Django 4.2 on 2024-10-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_unidaddemedida'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='precioInsumo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
