# Generated by Django 4.2 on 2024-10-31 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_cantidaddisponible'),
        ('productos', '0003_insumo_precioinsumo'),
    ]

    operations = [
    ]
