# Generated by Django 4.2 on 2024-10-16 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadPedida', models.PositiveIntegerField()),
                ('observaciones', models.TextField()),
                ('insumos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='productos.insumo')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('dni', models.CharField(max_length=8)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], max_length=10)),
                ('empresa', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecepcionPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDeRecepcion', models.DateTimeField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to='usuarios.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaPedido', models.DateTimeField()),
                ('estadoPedido', models.CharField(choices=[('confirmado', 'Confirmado'), ('pendiente', 'Pendiente'), ('cancelado', 'Cancelado')], max_length=10)),
                ('precioTotalDelPedido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedor', to='pedidos.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleRecepcionPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadRecibida', models.PositiveBigIntegerField()),
                ('estado', models.CharField(choices=[('completo', 'Completo'), ('incompleto', 'Incompleto')], max_length=10)),
                ('detallePedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detallePedido', to='pedidos.detallepedido')),
            ],
        ),
    ]
