# Generated by Django 4.2 on 2024-10-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fechaPedido',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='recepcionpedido',
            name='fechaDeRecepcion',
            field=models.DateField(),
        ),
    ]
