# Generated by Django 4.2 on 2024-10-26 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_pedido_fechapedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.pedido'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='subTotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='detallerecepcionpedido',
            name='detallePedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalleRecepcionPedido', to='pedidos.detallepedido'),
        ),
    ]
