# Generated by Django 4.2 on 2024-10-29 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_detallepedido_pedido_detallepedido_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallerecepcionpedido',
            name='recepcionPedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalleRecepcionPedido', to='pedidos.recepcionpedido'),
        ),
        migrations.AddField(
            model_name='recepcionpedido',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recepciones', to='pedidos.pedido'),
        ),
        migrations.AlterField(
            model_name='detallerecepcionpedido',
            name='cantidadRecibida',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='precioTotalDelPedido',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
