# Generated by Django 4.2 on 2024-11-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_detallerecepcionpedido_recepcionpedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detallerecepcionpedido',
            name='estado',
            field=models.CharField(choices=[('completo', 'Completo'), ('incompleto', 'Incompleto'), ('erroneo', 'Erroneo')], max_length=10),
        ),
    ]
