# Generated by Django 4.2 on 2024-10-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fechaDeIngreso',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fechaDeNacimiento',
            field=models.DateField(),
        ),
    ]
