# Generated by Django 4.2 on 2024-10-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_facturaafip_totalfactura_venta_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fechaDeVenta',
            field=models.DateField(),
        ),
    ]
