# Generated by Django 4.2 on 2024-10-22 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_venta_fechadeventa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacturaAfip',
        ),
    ]
