# Generated by Django 4.2 on 2024-10-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_alter_detalleventa_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientemayorista',
            name='cuil',
            field=models.CharField(max_length=13),
        ),
    ]
